### ISSUE TITLE
⚡️ v6.X Copy OTP code to clipboard after YubiKey touch

### ISSUE THREAD

**Issue by Rikj000** [Yubico/yubioath-flutter#867] opened 2022-12-06 14:44 UTC
## Issue description

In v5.X OTP codes where automatically copied to the clipboard after touching the YubiKey,   
which allows for a quick/smooth 2FA login flow.

However in v6.X you need to explicitly click the copy button after touching the YubiKey,   
which is an extra step compared to the v5.X flow, which makes it less quick/smooth to work with.

## Enhancement request
Directly copy the OTP codes to the clipboard after touching the YubiKey.

**Comment by dainnilsson** [comment] 2022-12-06 15:03
I believe this is a duplicate of #819.

**Closed by dainnilsson** 2022-12-06 15:03 UTC
