### ISSUE TITLE
Active key switching - better UX

### ISSUE THREAD

**Issue by msusta** [Yubico/yubioath-flutter#920] opened 2023-01-22 20:41 UTC
User can only interact with single key connected to the system. So users with multiple keys have to switch the active key within the application to see the OTP accounts.

In v5 the switch was part of the navigation menu (hamburger/left side of window depending on size) and key was listed there with icon, HW name and rolldown menu for selecting different key.

In v6 this was joined into the top-right corner in a similar way to how Google apps on Android allow you to change the active account.
This brought some good points and bad points:
+ Selector now shows the S/N
+ At least the icon is constantly visible without having to open the navigation menu like in v5
- Still requires number of clicks to select different key
- Even less information / worse visibility since only the icon of the key is visible
- The icon is _tiny_ - seems to be limited by the height of the search bar?

Some ideas / options:
* Having the selector in navigation menu - whenever the window is bigger now it still only shows the accounts in single column and the navmenu is quite empty
* Adding something like tabs / icon bar to the top of the screen with key selector (can be hidden with only one key inserted)

Overall - I'd love to achieve a way where I can see the keys in normal application use and change the key with a single click, since that's action I take many times during the day. Thanks for consideration!

**Comment by dainnilsson** [comment] 2023-01-25 18:44
Thanks for the feedback! We just released 6.1 which cuts down on the number of clicks needed to switch key, but we will continue to look over how we can continue to improve this further.

**Comment by msusta** [comment] 2023-01-26 13:12
@dainnilsson Thanks for the 6.1 changes. Leaving this open since I think something more can be done about it.

And putting a note about #625 which might help a lot with usability without the visual element.

**Comment by AdamVe** [comment] 2023-02-06 13:55
We are closing this as being duplicate of #823

**Closed by AdamVe** 2023-02-06 13:55 UTC
Labels: duplicate, enhancement
