### ISSUE TITLE
[Android] Fidesmo card not recognised after PR #820 merge (6.0.1 and later)

### ISSUE THREAD

**Issue by cegg1** [Yubico/yubioath-flutter#899] opened 2023-01-09 18:12 UTC
### Summary
The latest Android releases of Yubico Authenticator are longer recognising the Fidesmo card.

### Bug description
Yubioath-flutter releases up to [6.0.0 ](https://developers.yubico.com/yubioath-flutter/Releases/yubico-authenticator-6.0.0-android.apk)work fine with the Fidesmo card (OATH applet). The ability to recognise the Fidesmo card was broken in release [6.0.1](https://developers.yubico.com/yubioath-flutter/Releases/yubico-authenticator-6.0.1-android.apk). On version 6.0.1 or later, when tapping a Fidesmo card on the NFC reader, the app does not prompt for the password nor does it generate OTP codes. The phone vibrates indicating NFC detection.

**Error messages**
No error message is displayed in the app. 

![F600601](https://user-images.githubusercontent.com/28192843/211520191-57ef9828-7b1d-4036-9f9e-d1fcfbf6b2ad.png)

### Steps to reproduce

1) Install Yubico Authenticator [6.0.0 ](https://developers.yubico.com/yubioath-flutter/Releases/yubico-authenticator-6.0.0-android.apk)or earlier version, and launch the app. 
2) Tap a Fidesmo card (with OATH applet loaded) on the NFC reader. The phone vibrates. 
3) The app prompts for the password and the OTPs are generated sucessfully (**expected result**).

- **Now, update Yubico Authenticator to [6.0.1 ](https://developers.yubico.com/yubioath-flutter/Releases/yubico-authenticator-6.0.1-android.apk)or later version, and launch the app.** 
4) Tap a Fidesmo card (with OATH applet loaded) on the NFC reader. The phone vibrates. 
5) The app does **not** prompt for the password and does **not** compute the OTPs  (**actual result**).

### Suspected cause
Release notes for 6.0.1 contain a reference to "_Android: Fix connecting to YubiKey NEO over NFC on certain phones._". 
[PR #820](https://github.com/Yubico/yubioath-flutter/commit/3e335db55ff694dc516a01b1914713b270994522) "select OTP applet before reading device info" may be preventing the app from recognising the Fidesmo card. 

### Device info
Google Pixel 5
Android 13

**Comment by AdamVe** [comment] 2023-01-27 08:09
Hi, thank you for taking your time to report this issue. The goal of the Yubico Authenticator for Android application is to provide the best user experience for working with hardware keys manufactured by Yubico. The functionality of the app is adapted for the exposed interface of the YubiKey firmware. We don’t support and don’t plan to support products by other manufacturers (although they might work by coincidence).
I will review the patch you mention and try to figure out what could it break, but I sadly don’t have the card you mention, so I cannot do any testing.
To help to understand what is broken, could you create TRAFFIC logs from the version 6.0.0 and 6.0.1 and share those? The logs might expose user data, so please hide all the received bytes.

**Comment by AdamVe** [comment] 2023-01-31 09:44
@cegg1 I might have found the issue, but as I mentioned, I have no way how to test it with a real fidesmo card. I would like to ask you for help: could you get a patched build from [here](https://github.com/Yubico/yubioath-flutter/actions/runs/4052572666) and see if it fixes the issue? Note that this build is not signed with same certificate as the Google Play Store release so you will need to uninstall the app first.

**Comment by cegg1** [comment] 2023-02-02 19:27
Hi @AdamVe, 
thank you for looking into the issue. 

The [test build](https://github.com/Yubico/yubioath-flutter/actions/runs/4052572666) does not fix the issue, unfortunately. There is no difference in behaviour between 6.0.1 and the test build: no error message is shown. Releases 6.0.0 and earlier all work fine, while 6.0.1 and later don't work. Going back to this:

### 1- AID
There was only one commit made between 6.0.0 and 6.0.1, so this helps to narrow down the issue. 
In the [commit](https://github.com/Yubico/yubioath-flutter/commit/3e335db55ff694dc516a01b1914713b270994522), OathManager.kt was modified to add the OTP_AID = A000000527200101, as follows:

![Screenshot 2023-02-02 185748](https://user-images.githubusercontent.com/28192843/216423714-6eacb820-8e47-476f-a5f3-c3b022c44538.jpg)
But if we look at the [ykneo-oath](https://github.com/fidesmo/ykneo-oath/blob/master/build.gradle) code as published in Github, the AID should instead be A000000527210101:

![Screenshot 2023-02-02 185343](https://user-images.githubusercontent.com/28192843/216422361-85cf3bc5-b5e1-4904-9c8f-62097448fec6.jpg)

And if we refer to the [YKOATH Protocol Specification](https://developers.yubico.com/OATH/YKOATH_Protocol.html) in the develpers section, the AID is also listed as A000000527210101:

![s02](https://user-images.githubusercontent.com/28192843/216418421-2e9b2556-5bd8-4cdc-b309-d2f22ea5f983.jpg)

Is it possible the reason why the card isn't working in v>6.0.1 is that Authenticator is selecting the wrong AID? 
The fact is, the code that was in place before the [commit ](https://github.com/Yubico/yubioath-flutter/commit/3e335db55ff694dc516a01b1914713b270994522)was successful at communicating with the oath applet. 

### 2- Traffic
  _To help to understand what is broken, could you create TRAFFIC logs from the version 6.0.0 and 6.0.1 and share those?_ 

Sure. Can you please clarify if you want an ADB 'dumpsys nfc' or you mean NFC traffic interception with [NFCGate](https://github.com/nfcgate/nfcgate)? Happy to follow up with logs. 

### 3- Card
3) If all else fails, I can have a Fidesmo card delivered to you for testing purposes; please confirm which office is best to send it to.

**Comment by AdamVe** [comment] 2023-02-06 10:44
Hi @cegg1. The change in 6.0.1 is correct - we need to select the OTP app to avoid issues with YubiKey NEO when reading the device info. The OTP app will not exist on devices by other manufacturers and the select will throw. The change in the test build was to silently swallow that exception.

If the test build did not work, I could use help of the traffic logs. To create those logs do following:
1. restart the app
2. in the Help & About screen change the Log level to Traffic
3. close the Help & about screen
4. reproduce the issue by tapping your card against the NFC sensor
5. in the Help & About screen and use “Copy log” button - this will copy all the collected log to your phone’s clipboard.

Share the data from your clipboard in a new issue comment here on Github, but please have in mind that it contain sensitive information (account names and codes) - before posting it remove everything after the `TRAFFIC: received:` in every line. (If you have a card with only test data, which you don’t mind to be exposed, it is ok to send all of the logs)

If you have the possibility, please create test logs from the 6.0.0 and test build versions with the same card.

Currently we would like to solve this issue without any third-party hw, I will let you know if a physical card would be necessary.

Here is an example of log which I did with the test build and a test key:
<details>
  <summary>Test build log</summary>

```
[android.logger] INFO: Logging initialized, outputting to Android/logcat
[about] DEBUG: Log level set to TRAFFIC
[yubikit] TRAFFIC: nfc connection opened
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 21 01 01 
[yubikit] TRAFFIC: received: 79 03 00 02 01 71 08 7e e7 a6 f5 45 1a 85 dd 90 00 
[yubikit] TRAFFIC: sent: 00 a4 00 01 0a 74 08 00 00 00 00 03 54 4b 65 
[yubikit] TRAFFIC: received: 71 15 74 65 73 74 20 69 73 73 75 65 72 3a 74 65 73 74 20 6e 61 6d 65 76 05 06 21 20 aa d6 90 00 
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 20 01 01 
[yubikit] TRAFFIC: received: 03 04 01 03 8f 07 05 00 00 00 90 00 
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 47 11 17 
[yubikit] TRAFFIC: received: 6d 00 
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 20 01 01 
[yubikit] TRAFFIC: received: 03 04 01 03 8f 07 05 00 00 00 90 00 
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 47 11 17 
[yubikit] TRAFFIC: received: 6d 00 
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 20 01 01 
[yubikit] TRAFFIC: received: 03 04 01 03 8f 07 05 00 00 00 90 00 
[yubikit] TRAFFIC: sent: 00 01 10 00 00 
[yubikit] TRAFFIC: received: 00 3a 32 61 90 00 
[yubikit] TRAFFIC: Scan for available ccid applications
[yubikit] TRAFFIC: sent: 00 a4 04 00 06 d2 76 00 01 24 01 
[yubikit] TRAFFIC: received: 90 00 
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 21 01 01 
[yubikit] TRAFFIC: received: 79 03 00 02 01 71 08 7e e7 a6 f5 45 1a 85 dd 90 00 
[yubikit] TRAFFIC: sent: 00 a4 04 00 05 a0 00 00 03 08 
[yubikit] TRAFFIC: received: 61 11 4f 06 00 00 10 00 01 00 79 07 4f 05 a0 00 00 03 08 90 00 
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 06 47 2f 00 01 
[yubikit] TRAFFIC: received: 55 32 46 5f 56 32 90 00 
[yubikit] TRAFFIC: sent: 00 a4 04 00 07 a0 00 00 05 27 10 02 
[yubikit] TRAFFIC: received: 6d 00 
[yubikit] TRAFFIC: Missing applet AID_U2F_YUBICO, capability U2F
[yubikit] TRAFFIC: Read info z3.c@1b02fa0
[OathManager] DEBUG: Successfully read Oath session info (and credentials if unlocked) from connected key
[yubikit] TRAFFIC: nfc connection closed
[about] INFO: Copying log to clipboard (6.1.1-test)...
[android.logger] DEBUG: Getting logs...
```

</details>

**Comment by StarGate01** [comment] 2023-02-06 21:03
I also ran into this issue and debugged it. I found that to run the Authenticator against a TOTP/HOTP applet (`A0:00:00:05:27:21:01:01`), you also need to have an instance of a HMAC-SHA1 applet (`A0:00:00:05:27:20:01:01`) installed on the card in order for the app to fall back to the legacy protocol.

**Comment by cegg1** [comment] 2023-02-06 23:09
Hi @AdamVe, 
thank you for the clarification about traffic logs and for your interest in getting to the bottom of the issue. 
Below you can find traffic logs for all three versions, 6.0.0 (success), 6.0.1 (fail) and 6.1.1-test (fail).

### Traffic log using Authenticator 6.0.0 (success)
[android.logger] INFO: Logging initialized, outputting to Android/logcat
[about] DEBUG: Log level set to TRAFFIC
[yubikit] TRAFFIC: nfc connection opened
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 21 01 01
[yubikit] TRAFFIC: received: 79 03 00 ...data blob received... 21 90 00
**[OathManager] DEBUG: Successfully read Oath session info (and credentials if unlocked) from connected key**
[yubikit] TRAFFIC: nfc connection closed
[yubikit] TRAFFIC: nfc connection opened
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 47 11 17
[yubikit] TRAFFIC: received: 6a 82
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 20 01 01
[yubikit] TRAFFIC: received: 6a 82
**[yubikit] TRAFFIC: Couldn't select Management application, use fallback**
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 47 11 17
[yubikit] TRAFFIC: received: 6a 82
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 20 01 01
[yubikit] TRAFFIC: received: 6a 82
**[yubikit] TRAFFIC: Couldn't select OTP application, serial unknown
[yubikit] TRAFFIC: Firmware version unknown, using 3.0.0 as a baseline
[yubikit] TRAFFIC: Scan for available ccid applications**
[yubikit] TRAFFIC: sent: 00 a4 04 00 06 d2 76 00 01 24 01
[yubikit] TRAFFIC: received: 90 00
[yubikit] TRAFFIC: sent: 00 a4 04 00 07 a0 00 00 05 27 21 01
[yubikit] TRAFFIC: received: 79 03 00 ...data blob received... 21 90 00
[yubikit] TRAFFIC: sent: 00 a4 04 00 05 a0 00 00 03 08
[yubikit] TRAFFIC: received: 69 82
[yubikit] ERROR: IOException selecting applet PIV, capability PIV
[yubikit] ERROR(details): Unexpected SW
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 06 47 2f 00 01
[yubikit] TRAFFIC: received: 55 32 46 ...data blob received... 32 90 00
[yubikit] TRAFFIC: sent: 00 a4 04 00 07 a0 00 00 05 27 10 02
[yubikit] TRAFFIC: received: 6d 00
[yubikit] TRAFFIC: Missing applet AID_U2F_YUBICO, capability U2F
[yubikit] TRAFFIC: Read info v3.c@1efd8da
[yubikit] TRAFFIC: nfc connection closed
[yubikit] TRAFFIC: nfc connection opened
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 21 01 01
[yubikit] TRAFFIC: received: 79 03 00  ...data blob received...  21 90 00
[yubikit] TRAFFIC: sent: 00 a3 00 00 20 75 14 e4 77 f0 27 51 d7 6f e2 d5 b1 26 40 7b d0 97 ee 49 f6 e2 2c 74 08 9c e5 41 50 91 4d 23 a1
[yubikit] TRAFFIC: received: 75 14 03 ...data blob received... 8c 90 00
[yubikit] TRAFFIC: sent: 00 a4 00 01 0a 74 08 00 00 00 00 03 54 50 ca
[yubikit] TRAFFIC: received: 71 17 47 ...data blob received... 67 61 fc
[yubikit] TRAFFIC: sent: 00 a5 00 00 00
[yubikit] TRAFFIC: received: 31 33 40 ...data blob received... 71 61 fc
[yubikit] TRAFFIC: sent: 00 a5 00 00 00
[yubikit] TRAFFIC: received: 19 47 6f ...data blob received... c9 61 fc
[yubikit] TRAFFIC: sent: 00 a5 00 00 00
[yubikit] TRAFFIC: received: 85 5b 71 ...data blob received... 6e 61 8e
[yubikit] TRAFFIC: sent: 00 a5 00 00 00
[yubikit] TRAFFIC: received: 3a 63 65 ...data blob received... da 90 00
[yubikit] TRAFFIC: sent: 00 a4 00 01 0a 74 08 00 00 00 00 03 54 50 ca
[android.oath.state] DEBUG: applet unlocked
[yubikit] TRAFFIC: received: 71 17 47 ...data blob received... 67 61 fc
[yubikit] TRAFFIC: sent: 00 a5 00 00 00
[yubikit] TRAFFIC: received: 31 33 40...data blob received... 71 61 fc
[yubikit] TRAFFIC: sent: 00 a5 00 00 00
[yubikit] TRAFFIC: received: 19 47 6f ...data blob received... c9 61 fc
[yubikit] TRAFFIC: sent: 00 a5 00 00 00
[yubikit] TRAFFIC: received: 85 5b 71 ...data blob received... 6e 61 8e
[yubikit] TRAFFIC: sent: 00 a5 00 00 00
[yubikit] TRAFFIC: received: 3a 63 65 ...data blob received... da 90 00
**[OathManager] DEBUG: Successfully read Oath session info (and credentials if unlocked) from connected key**
[yubikit] TRAFFIC: nfc connection closed
[about] INFO: Copying log to clipboard (6.0.0)...
[android.logger] DEBUG: Getting logs...


### Traffic log using Authenticator 6.0.1 (fail)
[android.logger] INFO: Logging initialized, outputting to Android/logcat
[about] DEBUG: Log level set to TRAFFIC
[yubikit] TRAFFIC: nfc connection opened
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 21 01 01
[yubikit] TRAFFIC: received: 79 03 00 03 ...data blob received... 01 21 90 00
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 20 01 01
[yubikit] TRAFFIC: received: 69 82
**[OathManager] ERROR: Failed to connect to CCID
[OathManager] ERROR(details): java.io.IOException: Unexpected SW**
[yubikit] TRAFFIC: nfc connection closed
[about] INFO: Copying log to clipboard (6.0.1)...
[android.logger] DEBUG: Getting logs...


### Traffic log using Authenticator 6.1.1-test (fail)
[android.logger] INFO: Logging initialized, outputting to Android/logcat
[about] DEBUG: Log level set to TRAFFIC
[yubikit] TRAFFIC: nfc connection opened
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 21 01 01
[yubikit] TRAFFIC: received: 79 03 00 03 ...data blob received... 01 21 90 00
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 20 01 01
[yubikit] TRAFFIC: received: 69 82
**[OathManager] ERROR: Failed to select OTP - is this a YubiKey NEO?**
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 47 11 17
[yubikit] TRAFFIC: received: 69 82
**[OathManager] ERROR: Failed to connect to CCID
[OathManager] ERROR(details): java.io.IOException: Unexpected SW**
[yubikit] TRAFFIC: nfc connection closed
[about] INFO: Copying log to clipboard (6.1.1-test)...
[android.logger] DEBUG: Getting logs...

**Comment by cegg1** [comment] 2023-02-07 00:10
Hi @StarGate01, thank you for your feedback!
My understanding is the Fidesmo card has four applets, excluding development kits: [ykneo-oath](https://github.com/fidesmo/ykneo-oath), [ykneo-openpgp](https://github.com/fidesmo/ykneo-openpgp), the [Ledger FIDO-U2F](https://github.com/LedgerHQ/ledger-u2f-javacard) applet and the [Ledger Unplugged](https://github.com/LedgerHQ/ledger-javacard) bitcoin wallet. I don't think there is any HMAC-SHA1 applet in it. But the fact is that Authenticator 6.0.0 and earlier versions are able to select the [ykneo-oath](https://github.com/fidesmo/ykneo-oath) applet on the card successfully and work with it, whereas the same card fails when used with 6.0.1 and later.  The only difference between both versions of Authenticator is the way the AID is selected: the change was merged from [PR #820](https://github.com/Yubico/yubioath-flutter/commit/3e335db55ff694dc516a01b1914713b270994522).

**Comment by StarGate01** [comment] 2023-02-07 00:17
If you look at the log you posted above, the new version of the authenticator now fails if it cant find the HMAC-SHA1 - or as yubico calls it, [OTP](https://docs.yubico.com/software/yubikey/tools/ykman/OTP_Commands.html) - applet:

Old behaviour:
```
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 20 01 01
[yubikit] TRAFFIC: received: 6a 82
[yubikit] TRAFFIC: Couldn't select OTP application, serial unknown
[yubikit] TRAFFIC: Firmware version unknown, using 3.0.0 as a baseline
```

New behavior:
```
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 20 01 01
[yubikit] TRAFFIC: received: 69 82
[OathManager] ERROR: Failed to connect to CCID
```

If you have a Fidesmo developer account and permission for that AID, or a bare Javacard, you can deploy e.g. https://github.com/arekinath/YkOtpApplet and instantiate it using the AID a0 00 00 05 27 20 01 01 .

**Comment by cegg1** [comment] 2023-02-07 01:15
> If you have a Fidesmo developer account and permission for that AID, or a bare Javacard, you can deploy e.g. https://github.com/arekinath/YkOtpApplet and instantiate it using the AID a0 00 00 05 27 20 01 01.

I understand the concept, thanks. I am an end user, though, and none of those tools are readily available to me. 

> Alternatively, the authenticator could be modified to use the old fallback mechanism.

I think retaining compatibility within Authenticator would make more sense. It could be implemented as a setting that that comes disabled by default and the user has to select - e.g. "enable old fallback mechanism".

**Comment by AdamVe** [comment] 2023-02-07 07:28
Thank you both for the input, will look at this asap.

**Comment by AdamVe** [comment] 2023-02-08 10:36
I have analysed the logs for the three versions, thank you for sharing those, and found the problem. The change in 6.0.1 caused the OATH session to be reset and the same happened in the test build.
Now I have implemented a fix, which will prevent this - in the case of your card, the OATH session will not be reset, the device will itself be reported as Unknown OATH device.
Again, I tested this in a simulated environment, if you have a chance, please try the build (called 6.1.1-test-2) from here: https://github.com/Yubico/yubioath-flutter/actions/runs/4123090442

**Comment by StarGate01** [comment] 2023-02-08 11:11
@AdamVe I just tested your build, great success! The app now reads OTP codes without the card having the HMAC-SHA1 applet installed. The App identifies the TOTP applet as an "Unknown OATH device / Unknown type", presumably because no serial number is found - expected behavior.

Thank you for your effort!

**Comment by AdamVe** [comment] 2023-02-08 12:06
Thank you for taking your time to test the build @StarGate01!

**Comment by AdamVe** [comment] 2023-02-08 13:36
Thank you for confirmation and testing the build, @cegg1. This fix will be included in the next release.
I created a new issue for the double read.

**Comment by AdamVe** [comment] 2023-02-14 08:10
Yesterday we released version [6.1.1](https://github.com/Yubico/yubioath-flutter/releases/tag/6.1.1) which should fix this issue. @cegg1, give it a try, please.

**Comment by cegg1** [comment] 2023-02-20 16:01
Hi @AdamVe, I have tried the 6.1.1 version from Play Store and it works!

In case you're interested, something seems to happen when the oath device is tapped for the second time after (the after the password is typed) that the codes are not computed straight away, but simply tapping the device a third time works and all subsequent taps work fine. I've reproduced this by uninstalling/reinstalling the app and starting all over. In any case, from the user's perspective the 6.1.1 version of the app in Play Store is perfectly functional with the generic oath device. 

Thanks!


### Second tap (after typing the password)

> android.logger] INFO: Logging initialized, outputting to Android/logcat
> [about] DEBUG: Log level set to TRAFFIC
> [AppPreferences] DEBUG: unregistered change listener
> [MainActivity] DEBUG: Stopped usb discovery
> [MainActivity] DEBUG: Stopped nfc discovery
> [android.window_state_provider] DEBUG: appLifecycleStateChange triggered with: inactive
> [android.window_state_provider] DEBUG: Updated windowState to WindowState(focused: false, visible: false, active: false)
> [android.window_state_provider] DEBUG: appLifecycleStateChange triggered with: paused
> [android.window_state_provider] DEBUG: Ignoring appLifecycleStateChange
> [MainActivity] DEBUG: Starting nfc discovery
> [AppPreferences] DEBUG: registering change listener
> [android.window_state_provider] DEBUG: appLifecycleStateChange triggered with: resumed
> [android.window_state_provider] DEBUG: Updated windowState to WindowState(focused: true, visible: true, active: true)
> [yubikit] TRAFFIC: nfc connection opened
> [yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 21 01 01
> [yubikit] TRAFFIC: received: 79 03 ...data blob... 90 00
> [yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 20 01 01
> [yubikit] TRAFFIC: received: 69 82
> [OathManager] ERROR: Failed to recognize this OATH device.
> [OathManager] DEBUG: Successfully read Oath session info (and credentials if unlocked) from connected key
> [yubikit] TRAFFIC: nfc connection closed
> [yubikit] TRAFFIC: nfc connection opened
> [yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 21 01 01
> [yubikit] TRAFFIC: received: 79 03 ...data blob... 90 00
> [OathManager] DEBUG: Cancelled Dialog Unlocking
> [android.oath.state] DEBUG: Calling unlock failed with exception: PlatformException(CancellationException, java.util.concurrent.CancellationException, Cause: null, Stacktrace: java.util.concurrent.CancellationException
> at com.yubico.authenticator.oath.OathManager$u.q(Unknown Source:49)
> at com.yubico.authenticator.oath.OathManager$u.u(Unknown Source:8)
> at com.yubico.authenticator.oath.OathManager$u.b(Unknown Source:2)
> at g3.j$d.q(Unknown Source:30)
> at g3.j$d.t(Unknown Source:8)
> at g3.j$d.j(Unknown Source:4)
> at w5.b.b(Unknown Source:7)
> at r5.h.c(Unknown Source:49)
> at r5.g.c(Unknown Source:0)
> at g3.j.d(Unknown Source:70)
> at g3.j.a(Unknown Source:0)
> at g3.j$a.q(Unknown Source:42)
> at g3.j$a.t(Unknown Source:11)
> at g3.j$a.i(Unknown Source:6)
> at g3.e$b.q(Unknown Source:43)
> at c5.a.h(Unknown Source:11)
> at kotlinx.coroutines.internal.g.b(Unknown Source:132)
> at w5.a.c(Unknown Source:16)
> at w5.a.d(Unknown Source:5)
> at r5.j0.b(Unknown Source:41)
> at r5.a.B0(Unknown Source:0)
> at r5.h.a(Unknown Source:22)
> at r5.g.a(Unknown Source:0)
> at r5.h.b(Unknown Source:12)
> at r5.g.b(Unknown Source:0)
> at g3.e.d(Unknown Source:49)
> at g3.e.a(Unknown Source:0)
> at g3.d.f(Unknown Source:4)
> at r4.j$a.a(Unknown Source:17)
> at f4.c.j(Unknown Source:18)
> at f4.c.k(Unknown Source:20)
> at f4.c.g(Unknown Source:0)
> at f4.b.run(Unknown Source:12)
> at android.os.Handler.handleCallback(Handler.java:938)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loopOnce(Looper.java:201)
> at android.os.Looper.loop(Looper.java:288)
> at android.app.ActivityThread.main(ActivityThread.java:7870)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
> , null)
> [yubikit] TRAFFIC: sent: 00 a3 ...data blob... 9b af
> [yubikit] TRAFFIC: received: 75 14 ...data blob... 90 00
> [OathManager] ERROR: Failed to connect to CCID
> [OathManager] ERROR(details): java.lang.IllegalStateException: Already resumed
> [yubikit] TRAFFIC: nfc connection closed
> [about] INFO: Copying log to clipboard (6.1.1)...
> [android.logger] DEBUG: Getting logs...

### Third and subsequent taps 
[AppPreferences] DEBUG: unregistered change listener
[MainActivity] DEBUG: Stopped usb discovery
[MainActivity] DEBUG: Stopped nfc discovery
[android.window_state_provider] DEBUG: appLifecycleStateChange triggered with: inactive
[android.window_state_provider] DEBUG: Updated windowState to WindowState(focused: false, visible: false, active: false)
[android.window_state_provider] DEBUG: appLifecycleStateChange triggered with: paused
[android.window_state_provider] DEBUG: Ignoring appLifecycleStateChange
[MainActivity] DEBUG: Starting nfc discovery
[AppPreferences] DEBUG: registering change listener
[OathManager] DEBUG: Removing NFC data after resume.
[android.window_state_provider] DEBUG: appLifecycleStateChange triggered with: resumed
[android.window_state_provider] DEBUG: Updated windowState to WindowState(focused: true, visible: true, active: true)
[android.devices] DEBUG: Yubikey was detached.
[yubikit] TRAFFIC: nfc connection opened
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 21 01 01
[yubikit] TRAFFIC: received: 79 03 ...data blob... 90 00
[yubikit] TRAFFIC: sent: 00 a3 ...data blob... c1 51
[yubikit] TRAFFIC: received: 75 14 ...data blob... 90 00
[yubikit] TRAFFIC: sent: 00 a4 ...data blob... b4 b7
[yubikit] TRAFFIC: received: 71 17 ...data blob... 61 fc
[yubikit] TRAFFIC: sent: 00 a5 00 00 00
[yubikit] TRAFFIC: received: 31 33 ...data blob... 61 fc
[yubikit] TRAFFIC: sent: 00 a5 00 00 00
[yubikit] TRAFFIC: received: 19 47 ...data blob... 61 fc
[yubikit] TRAFFIC: sent: 00 a5 00 00 00
[yubikit] TRAFFIC: received: a4 0c ...data blob... 61 8e
[yubikit] TRAFFIC: sent: 00 a5 00 00 00
[yubikit] TRAFFIC: received: 3a 63 ...data blob...90 00
[yubikit] TRAFFIC: sent: 00 a4 ...data blob... 01 01
[yubikit] TRAFFIC: received: 6b 00
[OathManager] ERROR: Failed to recognize this OATH device.
[OathManager] DEBUG: Successfully read Oath session info (and credentials if unlocked) from connected key
[yubikit] TRAFFIC: nfc connection closed
[about] INFO: Copying log to clipboard (6.1.1)...
[android.logger] DEBUG: Getting logs...

**Comment by AdamVe** [comment] 2023-02-21 07:29
@cegg1 I am happy that 6.1.1 fixed the issue for you, thanks for confirmation, your time spent and all the logs you provided 👍🏻 I am closing this issue now. 

(I also created a new issue for the behaviour you described)

**Closed by AdamVe** 2023-02-21 07:29 UTC
Labels: enhancement, android
