### ISSUE TITLE
Linux arm64 Support

### ISSUE THREAD

**Issue by jwillikers** [Yubico/yubioath-flutter#616] opened 2020-06-06 13:39 UTC
I have a Pinebook Pro laptop which has arm64 processors. Would it be possible to release binaries for Linux arm64?

**Comment by dainnilsson** [comment] 2022-11-16 10:17
Yubico Authenticator 6.0 has now been released and uses a new codebase. As such, this issue has been marked with the `legacy` label, and will be automatically closed in 7 days. If this issue is still relevant to Yubico Authenticator 6, please comment on the issue saying so, and it will be kept open (or be re-opened). Sorry for the inconvenience!

**Comment by AdamVe** [comment] 2023-02-06 14:24
We will treat this as duplicate of #926.

**Closed by AdamVe** 2023-02-06 14:24 UTC
Labels: enhancement
